// hello-angular/src/app/login-form/login-form.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-login-form',
  templateUrl: './login-form.component.html',
  styleUrls: ['./login-form.component.css']
})
export class LoginFormComponent implements OnInit {

  credentials = {
    username: 'romain',
    password: '123456',
    rememberMe: true,
  };

  constructor() { }

  ngOnInit(): void {
  }

  verifyCredentials(event: Event) {
    // event.preventDefault();
    console.log(this.credentials);
  }
}

<!-- <form (submit)="verifyCredentials($event)">
  <div>
    Username : <input type="text" [value]="credentials.username" [className]="!credentials.username ? 'error':  ''" (input)="credentials.username = $any($event.target).value" />
  </div>
  <div>
    Password : <input type="password" [value]="credentials.password" (input)="credentials.password = $any($event.target).value" />
  </div>
  <div>
    <label>Remember me <input type="checkbox" [checked]="credentials.rememberMe" (input)="credentials.rememberMe = $any($event.target).checked" /></label>
  </div>
  <div>
    <button>Login</button>
  </div>
</form> -->


<form (submit)="verifyCredentials($event)">
  <!--
    formEl.addEventListener('submit', ($event) => {
      verifyCredentials($event)
      refreshUi();
    });
  -->
  <div>
    Username : <input name="username" type="text" [(ngModel)]="credentials.username" [className]="!credentials.username ? 'error':  ''">
  </div>
  <div>
    Password : <input name="password" type="password" [(ngModel)]="credentials.password" />
  </div>
  <div>
    <label>Remember me <input name="rememberMe" type="checkbox" [(ngModel)]="credentials.rememberMe" /></label>
    <!--
      checkboxEl.checked = credentials.rememberMe;
    -->
  </div>
  <div>
    <button>Login</button>
  </div>
</form>

// hello-vue/src/components/LoginForm.vue
<template>
<form @submit="verifyCredentials">
  <!--
    formEl.addEventListener('submit', ($event) => {
      verifyCredentials($event)
      refreshUi();
    });
  -->
  <div>
    Username : <input name="username" type="text" v-model="credentials.username" :className="!credentials.username ? 'error':  ''">
  </div>
  <div>
    Password : <input name="password" type="password" v-model="credentials.password" />
  </div>
  <div>
    <label>Remember me <input name="rememberMe" type="checkbox" v-model="credentials.rememberMe" /></label>
    <!--
      checkboxEl.checked = credentials.rememberMe;
    -->
  </div>
  <div>
    <button>Login</button>
  </div>
</form>

</template>

<script>
export default {
  name: 'LoginForm',
  data() {
    return {
      credentials: {
        username: 'romain',
        password: '123456',
        rememberMe: true,
      }
    };
  },
  methods: {
    verifyCredentials(event) {
      event.preventDefault();
      console.log(this.credentials);
    }
  }
}
</script>
