// hello-vue/src/views/Home.vue
<template>
  <div class="home">
    <h2>hello</h2>
    <Hello name="Romain"/>
    <h2>clock</h2>
    <Clock />
    <h2>counter</h2>
    <Counter />
    <h2>login-form</h2>
    <LoginForm />
    <h2>select</h2>
    <Select :selected="prenom" :items="prenoms" @selectedChange="prenom = $event" />
    <p>Vous avez sélectionné : {{prenom}}</p>
  </div>
</template>

<script>
// @ is an alias to /src
import Hello from '@/components/Hello.vue'
import Clock from '@/components/Clock.vue'
import Counter from '@/components/Counter.vue'
import LoginForm from '@/components/LoginForm.vue'
import Select from '@/components/Select.vue'

export default {
  name: 'Home',
  components: {
    Hello,
    Clock,
    Counter,
    LoginForm,
    Select
  },
  data() {
    return {
      prenoms: ['Toto', 'Titi', 'Tata'],
      prenom: 'Titi',
    }
  }
}
</script>

// hello-angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home', // document.querySelector('app-home')
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  prenom = 'Titi';
  prenoms = ['Toto', 'Titi', 'Tata'];

  constructor() { }

  ngOnInit(): void {
  }

}

<h2>hello</h2>
<app-hello></app-hello>
<app-hello name="Toto"></app-hello>
<app-hello [name]="prenom"></app-hello>

<h2>clock</h2>
<app-clock></app-clock>

<h2>counter</h2>
<app-counter></app-counter>

<h2>login-form</h2>
<app-login-form></app-login-form>

<h2>select</h2>
<app-select [selected]="prenom" [items]="prenoms" (selectedChange)="prenom = $event"></app-select>

<p>Vous avez sélectionné : {{ prenom }}</p>
