// hello-react/src/Todos.js
import { Component } from 'react';
import { fetchTodos } from './api';

class Todos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      inputValue: 'Beurre',
      todos: [
        { id: Math.random(), title: 'Pain', completed: true },
        { id: Math.random(), title: 'Lait', completed: false },
      ],
    };
  }
  componentDidMount() {
    const { todos } = this.state;
    fetchTodos().then((newTodos) => {
      this.setState({
        todos: [
          ...todos,
          ...newTodos
        ],
      });
    })
  }
  handleChange = (event) => {
    this.setState({
      inputValue: event.target.value,
    });
  }
  handleSubmit = (event) => {
    const { inputValue, todos } = this.state;
    event.preventDefault();
    this.setState({
      inputValue: '',
      todos: [
        ...todos,
        { id: Math.random(), title: inputValue, completed: false },
      ],
    });
  }
  handleDelete = (item) => {
    const { todos } = this.state;
    this.setState({
      todos: todos.filter((t) => t.id !== item.id),
    });
  }
  render() {
    const { inputValue, todos } = this.state;
    return (
      <div className="Todos" onSubmit={this.handleSubmit}>
        <form className="todos-form">
          <input className="todos-input" value={inputValue} onChange={this.handleChange} />
          <button>+</button>
        </form>
        <div className="todos-list">
          {todos.map((t, i) => (
            <div key={t.id}>
              <span>{t.title}</span>
              <button onClick={() => this.handleDelete(t)}>-</button>
            </div>
          ))}
        </div>
      </div>
    );
  }
}

export default Todos;

// hello-vue/src/views/Todos.vue
<template>
  <div class="Todos">
    <form class="todos-form" @submit="addTodo">
      <input name="newtodo" class="todos-input" v-model="inputValue" />
      <button>+</button>
    </form>
    <div class="todos-list">
      <div v-for="t in todos" :key="t.id">
        <span>{{ t.title }}</span>
        <button @click="deleteTodo(t)">-</button>
      </div>
    </div>
  </div>
</template>

<script>
import { fetchTodos } from '../api'

export default {
  name: 'Todos',
  data() {
    return {
      inputValue: 'Beurre',
      todos: [
        { id: Math.random(), title: 'Pain', completed: true },
        { id: Math.random(), title: 'Lait', completed: false },
      ],
    };
  },
  mounted() {
    fetchTodos().then((newTodos) => {
        this.todos = [
          ...this.todos, ...newTodos,
          ];
      })
  },
  methods: {
    addTodo(event) {
      event.preventDefault();
      this.todos = [
        ...this.todos,
        { id: Math.random(), title: this.inputValue, completed: false },
      ];
      this.inputValue = '';
    },
    deleteTodo(todo) {
      this.todos = this.todos.filter(t => t.id !== todo.id);
    },
  },
};
</script>
