// hello-react/src/Todos.js
import { Component } from 'react';

class Todos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      inputValue: 'Beurre',
      todos: [
        { id: Math.random(), title: 'Pain', completed: true },
        { id: Math.random(), title: 'Lait', completed: false },
      ],
    };
  }
  render() {
    return (
      <div className="Todos">
        <form class="todos-form">
          <input class="todos-input" />
          <button>+</button>
        </form>
        <div class="todos-list">
          {/* <div>
            <span>Pain</span>
          </div>
          <div>
            <span>Lait</span>
          </div> */}
        </div>
      </div>
    );
  }
}

export default Todos;

// hello-angular/src/app/todos/todos.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.css'],
})
export class TodosComponent implements OnInit {

  inputValue = 'Beurre';

  todos = [
    { id: Math.random(), title: 'Pain', completed: true },
    { id: Math.random(), title: 'Lait', completed: false },
  ];

  constructor() {}

  ngOnInit(): void {}
}

<form class="todos-form">
  <input class="todos-input">
  <button>+</button>
</form>
<div class="todos-list">
  <!-- <div>
    <span>Pain</span>
  </div>
  <div>
    <span>Lait</span>
  </div> -->
</div>
