// hello-vue/src/components/LoginForm.vue
<template>
<form @submit="verifyCredentials">
  <!--
    formEl.addEventListener('submit', ($event) => {
      verifyCredentials($event)
      refreshUi();
    });
  -->
  <div>
    Username : <input name="username" type="text" v-model="credentials.username" :className="!credentials.username ? 'error':  ''">
  </div>
  <div>
    Password : <input name="password" type="password" v-model="credentials.password" />
  </div>
  <div>
    <label>Remember me <input name="rememberMe" type="checkbox" v-model="credentials.rememberMe" /></label>
    <!--
      checkboxEl.checked = credentials.rememberMe;
    -->
  </div>
  <div>
    <button>Login</button>
  </div>
</form>

</template>

<script>
export default {
  name: 'LoginForm',
  data() {
    return {
      credentials: {
        username: 'romain',
        password: '123456',
        rememberMe: true,
      }
    };
  },
  methods: {
    verifyCredentials(event) {
      event.preventDefault();
      console.log(this.credentials);
    }
  }
}
</script>

// hello-react/src/LoginForm.js
import { Component } from 'react';

class LoginForm extends Component {
  constructor(props) {
    super(props);
    this.state = {
      username: 'romain',
      password: '123456',
      rememberMe: true,
    };
  }
  handleSubmit(event) {
    event.preventDefault();
    console.log(this.state);
  }
  render() {
    const { username, password, rememberMe } = this.state;
    return (
      <form className="LoginForm" onSubmit={(e) => this.handleSubmit(e)}>
        <div>
          Username :{' '}
          <input
            name="username"
            type="text"
            value={username}
            onChange={(e) => this.setState({ username: e.target.value })}
          />
        </div>
        <div>
          Password :{' '}
          <input
            name="password"
            type="password"
            value={password}
            onChange={(e) => this.setState({ password: e.target.value })}
          />
        </div>
        <div>
          <label>
            Remember me{' '}
            <input
              name="rememberMe"
              type="checkbox"
              checked={rememberMe}
              onChange={(e) => this.setState({ rememberMe: e.target.checked })}
            />
          </label>
        </div>
        <div>
          <button>Login</button>
        </div>
      </form>
    );
  }
}

export default LoginForm;
